### ISSUE TITLE
add JSON tag to mops entry so it shows up in search results

### ISSUE THREAD

**Issue by letmejustputthishere** [NatLabs/serde#1]
when i search for `json` on mops this library does not show up

**Comment by tomijaga** [comment]
Thanks for the suggestion!

I've added the keywords to the [mops.toml](https://github.com/NatLabs/serde/blob/main/mops.toml#L6) file to make the lib more discoverable.
However, the feature does not seem to be enabled in the current version of mops so I will open a PR with them and get it resolved.

**Comment by tomijaga** [comment]
The feature has been added and you now the `serde` lib shows up in the results when you search for `json` 
https://j4mwm-bqaaa-aaaam-qajbq-cai.ic0.app/#/search/json
