### ISSUE TITLE
Unable to catch error from `JSON.fromText`

### ISSUE THREAD

**Issue by ZenVoich** [NatLabs/serde#12]
`JSON.fromText` traps if unable to parse JSON text, and it is impossible to catch that.

 What if change it to return `?Blob` instead of `Blob`+trap?

**Comment by tomijaga** [comment]
Thanks for the PR!
I understand your frustration, as I recently faced this myself when trying to debug #9. 
I plan on updating the return type to  `Result<Blob, Text>` so successful requests return `#ok(Blob)` and failed requests return `#err(Text)` with an error message.

I'll let you know once I've made the changes and published them to mops.
