### ISSUE TITLE
Json.FromText fails with float types?

### ISSUE THREAD

**Issue by janusdotai** [NatLabs/serde#24]
Greetings,

I'm seeing the JSON parser fail when encountering a field with a FLOAT type?  For example, this works fine

` const data = "{\"code\":\"EUR\",\"alphaCode\":\"EUR\",\"numericCode\":\"978\",\"name\":\"Euro\",\"rate\": \"0.92365973383771\"}";`

but this does not:

` const data = "{\"code\":\"EUR\",\"alphaCode\":\"EUR\",\"numericCode\":\"978\",\"name\":\"Euro\",\"rate\": 0.92365973383771}";`

The 2nd example has a FLOAT type field for "rate" (the first example would be a string because its text-qualified)

When I run standard code like ` let t = JSON.fromText(data, null);  `  it throws an error for the 2nd case which is 

#err("Failed to parse JSON text")
![float serialization](https://github.com/NatLabs/serde/assets/100089505/92d5adf2-046d-43b6-9c0c-36934658feec)

Do you think its a problem with the Float type?  I could change my webservice to force text-qualify all fields as a work-around but I figured i'd report this potential issue to see if you were aware of it. Thank you.

**Comment by tomijaga** [comment]
Hello @janusdotai, thank you for reporting the issue. The library was missing support for floating point conversions. I created a pull request ([PR](https://github.com/aviate-labs/json.mo/pull/5)) a while ago to enable this feature in the JSON library but I didn't follow up to get it merged. 

I have now updated the library to support this feature and it's available in the [latest version](https://mops.one/serde/versions) on mops. 
Please let me know if you face any further issues.

**Comment by janusdotai** [comment]
Hi @tomijaga 

I'm trying to fetch data from coingecko and the float parsing works if there are decimals included ..but sometimes the api returns no decimal places.. when this happens, the float fails to parse.  Can you think of a workaround or is this an issue with the API being inconsistent?

https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd

returns:

{"bitcoin":{"usd":44920}}

https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=usd

{"ethereum":{"usd":2424.27}}

Not sure why CG isn't returning cents for btc .. but the JSON parser fails for float in this case.

![Capture](https://github.com/NatLabs/serde/assets/100089505/233a1914-a78b-4845-9169-52ace9fa1e5a)

thank you for helping

**Comment by tomijaga** [comment]
Hey @janusdotai ,
there's no way for the parser to differentiate between numbers (nats/ints) and floats other than the inclusion of decimal points. 

I could add another option in the parser to convert all numbers in the payload to floats. 

Something like 
```motoko
     let t = JSON.fromText(data, ?{ convertAllNumbersToFloat: true } ); 
```

Let me know if this will be enough to solve the current issue.
