### ISSUE TITLE
Motoko to JSON Multidimensional Aarray

### ISSUE THREAD

**Issue by krunalray** [NatLabs/serde#9]
i'm trying to convert multidimensional array to JSON but it is not working. it's give me Failed to decode candid blob kind of error.
in single array it's working good but multidimensional not working.
How to solve this error?

**Comment by tomijaga** [comment]
Hey @krunalray,  I wrote some [tests](https://github.com/NatLabs/serde/blob/main/tests/JSON.Test.mo#L188-L204) for converting the multi-dimensional array  but I wasn't able to recreate the issue you had. Can you share more details on the values and data type of the array?

**Comment by krunalray** [comment]
`type studentInfo = {
          name:Text;
          rollNo:Text;
         age:Text;                
  };

  type addressInfo = {
          firstname:Text;
          lastname:Text;
          address:Text;
          city:Text;
         pincode:Text;               
  };

   type subjectInfo = [{
          name:Text;
          marks:Text;
          grade:Text;
          remark:Text;                
  }];

    type student = {
         info:studentInfo;
         address_info:[addressInfo];
         subject:subjectInfo;
         subjectDataInfo: subjectInfo;               
   };

var info :T.studentInfo= {name = "name1"; rollNo = "1"; age="15";};

var subjectInfo :T.subjectInfo= [{name = "computer"; marks="90";grade= "a"; remark = "";},{name = "English"; marks="65";grade= "B"; remark = "";}];

var addressInfo :[T.addressInfo]= [{firstname = "firstname"; lastname="lastname";address= "address"; city = "city";pincode = "pincode"}];

  var studentData :T.student = {
        info = info;
        subject = subjectInfo;
        address_info = addressInfo;
        subjectDataInfo = subjectInfo;
  };

let postjsonn = JSON.toText(to_candid(studentData),[], null);
if i remove subjectDataInfo then it's working fine but if i used subjectDataInfo then it's give me an error.
Error:- trapped explicitly: Failed to decode candid blob
`

**Comment by tomijaga** [comment]
Hey @krunalray,

Thanks for posting more details about the issue. 
It helped find the root cause and request a [PR](https://github.com/edjCase/motoko_candid/issues/7) to fix it.

The PR has successfully merged, and the package has been updated on mops.
Try `serde@1.1.0` to resolve the issue.
